### ISSUE TITLE
[BUG] Literally getting a TOC inside each chapter

### ISSUE THREAD

**Issue by lalalasupa0** [maoserr/web_novel_to_epub#405]
**Describe the bug**
As the title says, I'm getting a table of contents inside each chapter when it shouldn't be as the table of contents should only be in its respective slot

**Required info:**
 - Url https://www.novelupdates.com/series/i-killed-the-player-of-the-academy/ with _Page Parse_ and in https://penguin-squad.com/story/i-killed-the-player-of-the-academy/ with _Links Parser_
   - Yeah, it happens in both, I would prefer to use the Penguin Squad website directly bc ch. 224 isn't on Novel Updates yet
     - I used [this](https://github.com/maoserr/epublifier/wiki#extracting-other-documentation) method for the Penguin Squad website from the home page where all chapters are listed
 - Browser Brave v1.71.121 Chromium: 130.0.6723.91
 - Extension Version 3.0.150

**Files:**
 - https://pixeldrain.com/u/dkwb4s9j (from the Penguin Squad website)
 - https://pixeldrain.com/u/YQSo3TkA (from Novel Updates)

**Additional:**

I've also tried using the next button, but it just reloads the page each time, Idk what I should've done there tbh
And I tried to do the same Links Parser thing but from the 1st chapter of the Penguin Squad website using the little index below but still got the same: https://pixeldrain.com/u/2nFiRmqX

**Proof:**

![Screenshot_20241108-223812](https://github.com/user-attachments/assets/7f9526da-618c-4df5-84ba-24990fe7bf90)

**Comment by maoserr** [comment]
This is not a bug, the page contains the full TOC on the left side menu. My parser can only extract what it reasonably thinks is the main content, it's not going to be 100%. It's up to the user to modify the parser definition if needed to clean up the html if so desired.

**Comment by lalalasupa0** [comment]
> This is not a bug, the page contains the full TOC on the left side menu. My parser can only extract what it reasonably thinks is the main content, it's not going to be 100%. It's up to the user to modify the parser definition if needed to clean up the html if so desired.

> It's up to the user to modify the parser definition if needed to clean up the html if so desired.

would love to know how to do that...
I see... Imma to have to put up with swiping every ch lol
I guess this should be closed?

**Comment by maoserr** [comment]
You can modify the parser definition as I have shown below, but for future requests, you need to figure out how to edit javascript yourself.

![image](https://github.com/user-attachments/assets/f711879e-5ece-4fd9-813c-05278e5922fe)
