### ISSUE TITLE
[BUG?] Not getting Footnotes on Genesis Studio

### ISSUE THREAD

**Issue by lalalasupa0** [maoserr/web_novel_to_epub#406]
**Describe the bug**
As the title says, I'm getting no footnotes in the resulting epub

**Required info (please complete the following information):**
 - Url https://genesistudio.com/viewer/833 (ch 21 of the wn) (footnotes at the end)
   - I used [this method](https://github.com/maoserr/epublifier/wiki#tranversing-webapp-through-next-button) to get it
 - Epub file https://pixeldrain.com/u/wsr5Z3wJ
 - Browser Brave v1.71.121 Chromium: 130.0.6723.91
 - Extension Version 3.0.150

I suppose waiting to get an exhaustive explanation of how to get them if it's already possible would be too much to hope for, but I'll still hope so

[It was said before](https://github.com/maoserr/epublifier/issues/398#issuecomment-2451857824) that this website would be difficult to make work, perhaps this is a result of that

**Comment by maoserr** [comment]
Yea, not a bug either. If you're not able to write javascript to modify the parser definition, you're out of luck.

I might consider adding some basic ability to modify the parser definition through non-code means at some point, but it would be a lot of work.
